
package br.com.bandtec.projetocontinuada3.anna;

public class TelaAtletas extends javax.swing.JFrame {
    
    
    Atletas nadadora = new Nadadora();
    Atletas lutadora = new Lutadora();
    Atletas jogador = new Jogador();
    Atletas ginasta = new Ginasta();
  
    public TelaAtletas(Usuario infoUsuario) {
        initComponents();
        
        // Mudando o valor das labels do perfil
        labelnome.setText(infoUsuario.getNome());
        labelnacionalidade.setText(Atletas.NACIONALIDADE);
        labelmensagem3.setText(Atletas.beberAgua());
        labelmodalidade.setText(infoUsuario.getEsporte());
        String modalidade = (infoUsuario.getEsporte());

    // Mensagem de acordo com atleta que for logado
    if (modalidade.equals("Luta")){
       
        labelmensagem1.setText(lutadora.treinar()); 
        labelidade.setText(Integer.toString(lutadora.idade));
        labelsexo.setText(lutadora.sexo);
        labelaltura.setText(Double.toString(lutadora.altura));
    } else if (modalidade.equals("Natação")){
        
        labelmensagem1.setText(nadadora.treinar());
        labelidade.setText(Integer.toString(nadadora.idade));
        labelsexo.setText(nadadora.sexo);
        labelaltura.setText(Double.toString(nadadora.altura));
    } else if (modalidade.equals("Futebol")){
        
        labelmensagem1.setText(jogador.treinar());
        labelidade.setText(Integer.toString(jogador.idade));
        labelsexo.setText(jogador.sexo);
        labelaltura.setText(Double.toString(jogador.altura));
    } else {
        
        labelmensagem1.setText(ginasta.treinar());
        labelidade.setText(Integer.toString(ginasta.idade));
        labelsexo.setText(ginasta.sexo);
        labelaltura.setText(Double.toString(ginasta.altura));
    }
        
        
    }

    private TelaAtletas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

      /*  labelidade.setText(uno2.trocarMarcha();;
        labelsexo.setText(infoUsuario.getSenha());
        labelaltura.setText(infoUsuario.getTelefone());
        labelnacionalidade.setText(infoUsuario.getTelefone());
        
        
        labelmensagem2.setText(nadadora.alongar());
        labelmensagem3.setText(nadadora.treinar()));
              /* uno1.trocarMarcha(); -- treinar !!! algo q vai diferente pra cada um
        uno2.trocarMarcha();
    
        Carro meuA4 = new AudiA4();
        meuA4.trocarMarcha();
        
        uno1.abastecer(); -- alongar !!  o mesmo pra todos
        meuA4.abastecer();
                
        
        
    }
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelnome = new javax.swing.JLabel();
        labelidade = new javax.swing.JLabel();
        labelsexo = new javax.swing.JLabel();
        labelaltura = new javax.swing.JLabel();
        labelnacionalidade = new javax.swing.JLabel();
        labelmensagem2 = new javax.swing.JLabel();
        labelmensagem3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelmensagem1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelmodalidade = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.NW_RESIZE_CURSOR));
        setForeground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel1.setText("NOME:");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel2.setText("IDADE:");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel3.setText("SEXO:");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel4.setText("ALTURA:");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel5.setText("NACIONALIDADE:");

        labelnome.setText("jLabel6");

        labelidade.setText("jLabel7");

        labelsexo.setText("jLabel8");

        labelaltura.setText("jLabel9");

        labelnacionalidade.setText("jLabel10");

        labelmensagem2.setText("--");

        labelmensagem3.setText("--");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel6.setText("PERFIL DO ATLETA ");

        labelmensagem1.setText("--");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel7.setText("MODALIDADE:");

        labelmodalidade.setText("jLabel8");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel8.setText("Rotina: ");

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel9.setText("1");

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel10.setText("2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelmensagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelmensagem3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                                        .addComponent(labelmensagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(labelnome))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(labelidade))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(24, 24, 24)
                                        .addComponent(labelsexo)))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(labelnacionalidade))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(labelmodalidade))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(29, 29, 29)
                                        .addComponent(labelaltura)))))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelnome)
                    .addComponent(jLabel4)
                    .addComponent(labelaltura))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelidade)
                    .addComponent(jLabel5)
                    .addComponent(labelnacionalidade))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelsexo)
                    .addComponent(jLabel7)
                    .addComponent(labelmodalidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelmensagem1)
                            .addComponent(jLabel9))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelmensagem3)
                            .addComponent(jLabel10)))
                    .addComponent(labelmensagem2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtletas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelaltura;
    private javax.swing.JLabel labelidade;
    private javax.swing.JLabel labelmensagem1;
    private javax.swing.JLabel labelmensagem2;
    private javax.swing.JLabel labelmensagem3;
    private javax.swing.JLabel labelmodalidade;
    private javax.swing.JLabel labelnacionalidade;
    private javax.swing.JLabel labelnome;
    private javax.swing.JLabel labelsexo;
    // End of variables declaration//GEN-END:variables
}
